(pkg-config-cflags "sdl2" :optional t)
(include "SDL2/SDL.h")

(in-package #:cl-sdl2-cffi)

;; Constants
(constant (+SDL-INIT-TIMER+ "SDL_INIT_TIMER"))
(constant (+SDL-INIT-AUDIO+ "SDL_INIT_AUDIO"))
(constant (+SDL-INIT-VIDEO+ "SDL_INIT_VIDEO"))
(constant (+SDL-INIT-JOYSTICK+ "SDL_INIT_JOYSTICK"))
(constant (+SDL-INIT-HAPTIC+ "SDL_INIT_HAPTIC"))
(constant (+SDL-INIT-GAMECONTROLLER+ "SDL_INIT_GAMECONTROLLER"))
(constant (+SDL-INIT-EVENTS+ "SDL_INIT_EVENTS"))
(constant (+SDL-INIT-SENSOR+ "SDL_INIT_SENSOR"))
(constant (+SDL-INIT-NOPARACHUTE+ "SDL_INIT_NOPARACHUTE"))
(constant (+SDL-INIT-EVERYTHING+ "SDL_INIT_EVERYTHING"))

;; basic types
(ctype size-t "size_t")

;; SDL_stdinc.h
(cenum sdl-bool
       ((:FALSE "SDL_FALSE"))
       ((:TRUE "SDL_TRUE")))

;; SDL_pixels.h
(constant (+SDL-ALPHA-OPAQUE+ "SDL_ALPHA_OPAQUE"))
(constant (+SDL-ALPHA-TRANSPARENT+ "SDL_ALPHA_TRANSPARENT"))

(cenum sdl-pixeltype
       ((:UNKNOWN "SDL_PIXELTYPE_UNKNOWN"))
       ((:INDEX1 "SDL_PIXELTYPE_INDEX1"))
       ((:INDEX4 "SDL_PIXELTYPE_INDEX4"))
       ((:INDEX8 "SDL_PIXELTYPE_INDEX8"))
       ((:PACKED8 "SDL_PIXELTYPE_PACKED8"))
       ((:PACKED16 "SDL_PIXELTYPE_PACKED16"))
       ((:PACKED32 "SDL_PIXELTYPE_PACKED32"))
       ((:ARRAYU8 "SDL_PIXELTYPE_ARRAYU8"))
       ((:ARRAYU16 "SDL_PIXELTYPE_ARRAYU16"))
       ((:ARRAYU32 "SDL_PIXELTYPE_ARRAYU32"))
       ((:ARRAYF16 "SDL_PIXELTYPE_ARRAYF16"))
       ((:ARRAYF32 "SDL_PIXELTYPE_ARRAYF32")))

(cenum sdl-packedorder
       ((:NONE "SDL_PACKEDORDER_NONE"))
       ((:XRGB "SDL_PACKEDORDER_XRGB"))
       ((:RGBX "SDL_PACKEDORDER_RGBX"))
       ((:ARGB "SDL_PACKEDORDER_ARGB"))
       ((:RGBA "SDL_PACKEDORDER_RGBA"))
       ((:XBGR "SDL_PACKEDORDER_XBGR"))
       ((:BGRX "SDL_PACKEDORDER_BGRX"))
       ((:ABGR "SDL_PACKEDORDER_ABGR"))
       ((:BGRA "SDL_PACKEDORDER_BGRA")))

(cenum sdl-arrayorder
       ((:NONE "SDL_ARRAYORDER_NONE"))
       ((:RGB "SDL_ARRAYORDER_RGB"))
       ((:RGBA "SDL_ARRAYORDER_RGBA"))
       ((:ARGB "SDL_ARRAYORDER_ARGB"))
       ((:BGR "SDL_ARRAYORDER_BGR"))
       ((:BGRA "SDL_ARRAYORDER_BGRA"))
       ((:ABGR "SDL_ARRAYORDER_ABGR")))

(cenum sdl-packedlayout
       ((:NONE "SDL_PACKEDLAYOUT_NONE"))
       ((:332 "SDL_PACKEDLAYOUT_332"))
       ((:4444 "SDL_PACKEDLAYOUT_4444"))
       ((:1555 "SDL_PACKEDLAYOUT_1555"))
       ((:5551 "SDL_PACKEDLAYOUT_5551"))
       ((:565 "SDL_PACKEDLAYOUT_565"))
       ((:8888 "SDL_PACKEDLAYOUT_8888"))
       ((:2101010 "SDL_PACKEDLAYOUT_2101010"))
       ((:1010102 "SDL_PACKEDLAYOUT_1010102")))

(cenum sdl-pixelformatenum
       ((:INDEX1LSB "SDL_PIXELFORMAT_INDEX1LSB"))
       ((:INDEX1MSB "SDL_PIXELFORMAT_INDEX1MSB"))
       ((:INDEX4LSB "SDL_PIXELFORMAT_INDEX4LSB"))
       ((:INDEX4MSB "SDL_PIXELFORMAT_INDEX4MSB"))
       ((:INDEX8 "SDL_PIXELFORMAT_INDEX8"))
       ((:RGB332 "SDL_PIXELFORMAT_RGB332"))
       ((:XRGB4444 "SDL_PIXELFORMAT_XRGB4444"))
       ((:RGB444 "SDL_PIXELFORMAT_RGB444"))
       ((:XBGR4444 "SDL_PIXELFORMAT_XBGR4444"))
       ((:BGR444 "SDL_PIXELFORMAT_BGR444"))
       ((:XRGB1555 "SDL_PIXELFORMAT_XRGB1555"))
       ((:RGB555 "SDL_PIXELFORMAT_RGB555"))
       ((:XBGR1555 "SDL_PIXELFORMAT_XBGR1555"))
       ((:BGR555 "SDL_PIXELFORMAT_BGR555"))
       ((:ARGB4444 "SDL_PIXELFORMAT_ARGB4444"))
       ((:RGBA4444 "SDL_PIXELFORMAT_RGBA4444"))
       ((:ABGR4444 "SDL_PIXELFORMAT_ABGR4444"))
       ((:BGRA4444 "SDL_PIXELFORMAT_BGRA4444"))
       ((:ARGB1555 "SDL_PIXELFORMAT_ARGB1555"))
       ((:RGBA5551 "SDL_PIXELFORMAT_RGBA5551"))
       ((:ABGR1555 "SDL_PIXELFORMAT_ABGR1555"))
       ((:BGRA5551 "SDL_PIXELFORMAT_BGRA5551"))
       ((:RGB565 "SDL_PIXELFORMAT_RGB565"))
       ((:BGR565 "SDL_PIXELFORMAT_BGR565"))
       ((:RGB24 "SDL_PIXELFORMAT_RGB24"))
       ((:BGR24 "SDL_PIXELFORMAT_BGR24"))
       ((:XRGB8888 "SDL_PIXELFORMAT_XRGB8888"))
       ((:RGB888 "SDL_PIXELFORMAT_RGB888"))
       ((:RGBX8888 "SDL_PIXELFORMAT_RGBX8888"))
       ((:XBGR8888 "SDL_PIXELFORMAT_XBGR8888"))
       ((:BGR888 "SDL_PIXELFORMAT_BGR888"))
       ((:BGRX8888 "SDL_PIXELFORMAT_BGRX8888"))
       ((:ARGB8888 "SDL_PIXELFORMAT_ARGB8888"))
       ((:RGBA8888 "SDL_PIXELFORMAT_RGBA8888"))
       ((:ABGR8888 "SDL_PIXELFORMAT_ABGR8888"))
       ((:BGRA8888 "SDL_PIXELFORMAT_BGRA8888"))
       ((:ARGB2101010 "SDL_PIXELFORMAT_ARGB2101010"))
       ((:RGBA32 "SDL_PIXELFORMAT_RGBA32"))
       ((:ARGB32 "SDL_PIXELFORMAT_ARGB32"))
       ((:BGRA32 "SDL_PIXELFORMAT_BGRA32"))
       ((:ABGR32 "SDL_PIXELFORMAT_ABGR32"))
       ((:YV12 "SDL_PIXELFORMAT_YV12"))
       ((:IYUV "SDL_PIXELFORMAT_IYUV"))
       ((:YUY2 "SDL_PIXELFORMAT_YUY2"))
       ((:UYVY "SDL_PIXELFORMAT_UYVY"))
       ((:YVYU "SDL_PIXELFORMAT_YVYU"))
       ((:NV12 "SDL_PIXELFORMAT_NV12"))
       ((:NV21 "SDL_PIXELFORMAT_NV21"))
       ((:EXTERNAL-OES "SDL_PIXELFORMAT_EXTERNAL_OES")))

(cstruct sdl-color "SDL_Color"
         (:r "r" :type Uint8)
         (:g "g" :type Uint8)
         (:b "b" :type Uint8)
         (:a "a" :type Uint8))

(cstruct sdl-palette "SDL_Palette"
         (:ncolors "ncolors" :type :int)
         (:colors "colors" :type :pointer)
         (:refcount "refcount" :type :int))

(cstruct sdl-pixelformat "SDL_PixelFormat"
         (:format "format" :type Uint32)
         (:palette "palette" :type :pointer)
         (:BitsPerPixel "BitsPerPixel" :type Uint8)
         (:BytesPerPixel "BytesPerPixel" :type Uint8)
         (:padding "padding" :type Uint8 :count 2)
         (:Rmask "Rmask" :type Uint32)
         (:Gmask "Gmask" :type Uint32)
         (:Bmask "Bmask" :type Uint32)
         (:Amask "Amask" :type Uint32)
         (:Rloss "Rloss" :type Uint8)
         (:Gloss "Gloss" :type Uint8)
         (:Bloss "Bloss" :type Uint8)
         (:Aloss "Aloss" :type Uint8)
         (:Rshift "Rshift" :type Uint8)
         (:Gshift "Gshift" :type Uint8)
         (:Bshift "Bshift" :type Uint8)
         (:Ashift "Ashift" :type Uint8)
         (:refcount "refcount" :type :int)
         (:next "next" :type :pointer))

;; SDL_rect.h
(cstruct sdl-point "SDL_Point"
         (:x "x" :type :int)
         (:y "y" :type :int))

(cstruct sdl-point "SDL_FPoint"
         (:x "x" :type :float)
         (:y "y" :type :float))

(cstruct sdl-rect "SDL_Rect"
         (:x "x" :type :int)
         (:y "y" :type :int)
         (:w "w" :type :int)
         (:h "h" :type :int))

(cstruct sdl-rect "SDL_FRect"
         (:x "x" :type :float)
         (:y "y" :type :float)
         (:w "w" :type :float)
         (:h "h" :type :float))

;; SDL_blendmode.h
(cenum sdl-blend-mode
       ((:NONE "SDL_BLENDMODE_NONE"))
       ((:BLEND "SDL_BLENDMODE_BLEND"))
       ((:ADD "SDL_BLENDMODE_ADD"))
       ((:MOD "SDL_BLENDMODE_MOD"))
       ((:MUL "SDL_BLENDMODE_MUL"))
       ((:INVALID "SDL_BLENDMODE_INVALID")))

(cenum sdl-blend-operation
       ((:ADD "SDL_BLENDOPERATION_ADD"))
       ((:SUBTRACT "SDL_BLENDOPERATION_SUBTRACT"))
       ((:REV-SUBTRACT "SDL_BLENDOPERATION_REV_SUBTRACT"))
       ((:MINIMUM "SDL_BLENDOPERATION_MINIMUM"))
       ((:MAXIMUM "SDL_BLENDOPERATION_MAXIMUM")))

(cenum sdl-blend-factor
       ((:ZERO "SDL_BLENDFACTOR_ZERO"))
       ((:ONE "SDL_BLENDFACTOR_ONE"))
       ((:SRC-COLOR "SDL_BLENDFACTOR_SRC_COLOR"))
       ((:ONE-MINUS-SRC-COLOR "SDL_BLENDFACTOR_ONE_MINUS_SRC_COLOR"))
       ((:SRC-ALPHA "SDL_BLENDFACTOR_SRC_ALPHA"))
       ((:ONE-MINUS-SRC-ALPHA "SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA"))
       ((:DST-COLOR "SDL_BLENDFACTOR_DST_COLOR"))
       ((:ONE-MINUS-DST-COLOR "SDL_BLENDFACTOR_ONE_MINUS_DST_COLOR"))
       ((:DST-ALPHA "SDL_BLENDFACTOR_DST_ALPHA"))
       ((:ONE-MINUS-DST-ALPHA "SDL_BLENDFACTOR_ONE_MINUS_DST_ALPHA")))

;; SDL_surface.h
(constant (+SDL-SWSURFACE "SDL_SWSURFACE"))
(constant (+SDL-PREALLOC+ "SDL_PREALLOC"))
(constant (+SDL-RLEACCEL+ "SDL_RLEACCEL"))
(constant (+SDL-DONTFREE+ "SDL_DONTFREE"))
(constant (+SDL-SIMD-ALIGNED+ "SDL_SIMD_ALIGNED"))

(cstruct sdl-surface "SDL_Surface"
         (:flags "flags" :type Uint32)
         (:format "format" :type :pointer)
         (:w "w" :type :int)
         (:h "h" :type :int)
         (:pitch "pitch" :type :int)
         (:pixels "pixels" :type :pointer)
         (:userdata "userdata" :type :pointer)
         (:locked "locked" :type :int)
         (:list_blitmap "list_blitmap" :type :pointer)
         (:clip_rect "clip_rect" :type sdl-rect)
         (:map "map" :type :pointer)
         (:refcount "refcount" :type :int))

(cenum sdl-yuv-conversion-mode
       ((:JPEG "SDL_YUV_CONVERSION_JPEG"))
       ((:BT601 "SDL_YUV_CONVERSION_BT601"))
       ((:BT709 "SDL_YUV_CONVERSION_BT709"))
       ((:AUTOMATIC "SDL_YUV_CONVERSION_AUTOMATIC")))

;; SDL_timer.h
(ctype sdl-timer-id "SDL_TimerID")

;; SDL_gamecontroller.h

;; SDL_video.h
(cstruct sdl-display-mode "SDL_DisplayMode"
         (:format "format" :type Uint32)
         (:w "w" :type :int)
         (:h "h" :type :int)
         (:refresh_rate "refresh_rate" :type :int)
         (:driverdata "driverdata" :type :pointer))

(cenum sdl-window-flags
       ((:FULLSCREEN "SDL_WINDOW_FULLSCREEN"))
       ((:OPENGL "SDL_WINDOW_OPENGL"))
       ((:SHOWN "SDL_WINDOW_SHOWN"))
       ((:HIDDEN "SDL_WINDOW_HIDDEN"))
       ((:BORDERLESS "SDL_WINDOW_BORDERLESS"))
       ((:RESIZABLE "SDL_WINDOW_RESIZABLE"))
       ((:MINIMIZED "SDL_WINDOW_MINIMIZED"))
       ((:MAXIMIZED "SDL_WINDOW_MAXIMIZED"))
       ((:INPUT-GRABBED "SDL_WINDOW_INPUT_GRABBED"))
       ((:INPUT-FOCUS "SDL_WINDOW_INPUT_FOCUS"))
       ((:MOUSE-FOCUS "SDL_WINDOW_MOUSE_FOCUS"))
       ((:FULLSCREEN-DESKTOP "SDL_WINDOW_FULLSCREEN_DESKTOP"))
       ((:FOREIGN "SDL_WINDOW_FOREIGN"))
       ((:ALLOW-HIGHDPI "SDL_WINDOW_ALLOW_HIGHDPI"))
       ((:MOUSE-CAPTURE "SDL_WINDOW_MOUSE_CAPTURE"))
       ((:ALWAYS-ON-TOP "SDL_WINDOW_ALWAYS_ON_TOP"))
       ((:SKIP-TASKBAR "SDL_WINDOW_SKIP_TASKBAR"))
       ((:UTILITY "SDL_WINDOW_UTILITY"))
       ((:TOOLTIP "SDL_WINDOW_TOOLTIP"))
       ((:POPUP-MENU "SDL_WINDOW_POPUP_MENU"))
       ((:VULKAN "SDL_WINDOW_VULKAN"))
       ((:METAL "SDL_WINDOW_METAL")))

(cenum sdl-window-event-id
       ((:NONE "SDL_WINDOWEVENT_NONE"))
       ((:SHOWN "SDL_WINDOWEVENT_SHOWN"))
       ((:HIDDEN "SDL_WINDOWEVENT_HIDDEN"))
       ((:EXPOSED "SDL_WINDOWEVENT_EXPOSED"))
       ((:MOVED "SDL_WINDOWEVENT_MOVED"))
       ((:RESIZED "SDL_WINDOWEVENT_RESIZED"))
       ((:SIZE-CHANGED "SDL_WINDOWEVENT_SIZE_CHANGED"))
       ((:MINIMIZED "SDL_WINDOWEVENT_MINIMIZED"))
       ((:MAXIMIZED "SDL_WINDOWEVENT_MAXIMIZED"))
       ((:RESTORED "SDL_WINDOWEVENT_RESTORED"))
       ((:ENTER "SDL_WINDOWEVENT_ENTER"))
       ((:LEAVE "SDL_WINDOWEVENT_LEAVE"))
       ((:FOCUS-GAINED "SDL_WINDOWEVENT_FOCUS_GAINED"))
       ((:FOCUS-LOST "SDL_WINDOWEVENT_FOCUS_LOST"))
       ((:CLOSE "SDL_WINDOWEVENT_CLOSE"))
       ((:TAKE-FOCUS "SDL_WINDOWEVENT_TAKE_FOCUS"))
       ((:HIT-TEST "SDL_WINDOWEVENT_HIT_TEST")))

(cenum sdl-display-event-id
       ((:NONE "SDL_DISPLAYEVENT_NONE"))
       ((:ORIENTATION "SDL_DISPLAYEVENT_ORIENTATION"))
       ((:CONNECTED "SDL_DISPLAYEVENT_CONNECTED"))
       ((:DISCONNECTED "SDL_DISPLAYEVENT_DISCONNECTED")))

(cenum sdl-display-orientation
       ((:UNKNOWN "SDL_ORIENTATION_UNKNOWN"))
       ((:LANDSCAPE "SDL_ORIENTATION_LANDSCAPE"))
       ((:LANDSCAPE-FLIPPED "SDL_ORIENTATION_LANDSCAPE_FLIPPED"))
       ((:PORTRAIT "SDL_ORIENTATION_PORTRAIT"))
       ((:PORTRAIT-FLIPPED "SDL_ORIENTATION_PORTRAIT_FLIPPED")))

(cenum sdl-gl-attr
       ((:RED-SIZE "SDL_GL_RED_SIZE"))
       ((:GREEN-SIZE "SDL_GL_GREEN_SIZE"))
       ((:BLUE-SIZE "SDL_GL_BLUE_SIZE"))
       ((:ALPHA-SIZE "SDL_GL_ALPHA_SIZE"))
       ((:BUFFER-SIZE "SDL_GL_BUFFER_SIZE"))
       ((:DOUBLEBUFFER "SDL_GL_DOUBLEBUFFER"))
       ((:DEPTH-SIZE "SDL_GL_DEPTH_SIZE"))
       ((:STENCIL-SIZE "SDL_GL_STENCIL_SIZE"))
       ((:ACCUM-RED-SIZE "SDL_GL_ACCUM_RED_SIZE"))
       ((:ACCUM-GREEN-SIZE "SDL_GL_ACCUM_GREEN_SIZE"))
       ((:ACCUM-BLUE-SIZE "SDL_GL_ACCUM_BLUE_SIZE"))
       ((:ACCUM-ALPHA-SIZE "SDL_GL_ACCUM_ALPHA_SIZE"))
       ((:STEREO "SDL_GL_STEREO"))
       ((:MULTISAMPLEBUFFERS "SDL_GL_MULTISAMPLEBUFFERS"))
       ((:MULTISAMPLESAMPLES "SDL_GL_MULTISAMPLESAMPLES"))
       ((:ACCELERATED-VISUAL "SDL_GL_ACCELERATED_VISUAL"))
       ((:RETAINED-BACKING "SDL_GL_RETAINED_BACKING"))
       ((:CONTEXT-MAJOR-VERSION "SDL_GL_CONTEXT_MAJOR_VERSION"))
       ((:CONTEXT-MINOR-VERSION "SDL_GL_CONTEXT_MINOR_VERSION"))
       ((:CONTEXT-EGL "SDL_GL_CONTEXT_EGL"))
       ((:CONTEXT-FLAGS "SDL_GL_CONTEXT_FLAGS"))
       ((:CONTEXT-PROFILE-MASK "SDL_GL_CONTEXT_PROFILE_MASK"))
       ((:SHARE-WITH-CURRENT-CONTEXT "SDL_GL_SHARE_WITH_CURRENT_CONTEXT"))
       ((:FRAMEBUFFER-SRGB-CAPABLE "SDL_GL_FRAMEBUFFER_SRGB_CAPABLE"))
       ((:CONTEXT-RELEASE-BEHAVIOR "SDL_GL_CONTEXT_RELEASE_BEHAVIOR"))
       ((:CONTEXT-RESET-NOTIFICATION "SDL_GL_CONTEXT_RESET_NOTIFICATION"))
       ((:CONTEXT-NO-ERROR "SDL_GL_CONTEXT_NO_ERROR")))

(cenum sdl-gl-profile
       ((:CORE
         "SDL_GL_CONTEXT_PROFILE_CORE"))
       ((:COMPATIBILITY
         "SDL_GL_CONTEXT_PROFILE_COMPATIBILITY"))
       ((:ES
         "SDL_GL_CONTEXT_PROFILE_ES")))

(cenum sdl-gl-context-flag
       ((:DEBUG
         "SDL_GL_CONTEXT_DEBUG_FLAG"))
       ((:FORWARD-COMPATIBLE
         "SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG"))
       ((:ROBUST-ACCESS
         "SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG"))
       ((:RESET-ISOLATION
         "SDL_GL_CONTEXT_RESET_ISOLATION_FLAG")))

(cenum sdl-gl-context-release-flag
       ((:NONE
         "SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE"))
       ((:FLUSH
         "SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH")))

(cenum sdl-gl-context-reset-notification
       ((:NO-NOTIFICATION "SDL_GL_CONTEXT_RESET_NO_NOTIFICATION"))
       ((:LOSE-CONTEXT "SDL_GL_CONTEXT_RESET_LOSE_CONTEXT")))

(cenum sdl-hit-test-result
       ((:NORMAL "SDL_HITTEST_NORMAL"))
       ((:DRAGGABLE "SDL_HITTEST_DRAGGABLE"))
       ((:RESIZE-TOPLEFT "SDL_HITTEST_RESIZE_TOPLEFT"))
       ((:RESIZE-TOP "SDL_HITTEST_RESIZE_TOP"))
       ((:RESIZE-TOPRIGHT "SDL_HITTEST_RESIZE_TOPRIGHT"))
       ((:RESIZE-RIGHT "SDL_HITTEST_RESIZE_RIGHT"))
       ((:RESIZE-BOTTOMRIGHT "SDL_HITTEST_RESIZE_BOTTOMRIGHT"))
       ((:RESIZE-BOTTOM "SDL_HITTEST_RESIZE_BOTTOM"))
       ((:RESIZE-BOTTOMLEFT "SDL_HITTEST_RESIZE_BOTTOMLEFT"))
       ((:RESIZE-LEFT "SDL_HITTEST_RESIZE_LEFT")))

;; SDL_scancode.h
(cenum sdl-scancode
       ((:UNKNOWN "SDL_SCANCODE_UNKNOWN"))

       ((:A "SDL_SCANCODE_A"))
       ((:B "SDL_SCANCODE_B"))
       ((:C "SDL_SCANCODE_C"))
       ((:D "SDL_SCANCODE_D"))
       ((:E "SDL_SCANCODE_E"))
       ((:F "SDL_SCANCODE_F"))
       ((:G "SDL_SCANCODE_G"))
       ((:H "SDL_SCANCODE_H"))
       ((:I "SDL_SCANCODE_I"))
       ((:J "SDL_SCANCODE_J"))
       ((:K "SDL_SCANCODE_K"))
       ((:L "SDL_SCANCODE_L"))
       ((:M "SDL_SCANCODE_M"))
       ((:N "SDL_SCANCODE_N"))
       ((:O "SDL_SCANCODE_O"))
       ((:P "SDL_SCANCODE_P"))
       ((:Q "SDL_SCANCODE_Q"))
       ((:R "SDL_SCANCODE_R"))
       ((:S "SDL_SCANCODE_S"))
       ((:T "SDL_SCANCODE_T"))
       ((:U "SDL_SCANCODE_U"))
       ((:V "SDL_SCANCODE_V"))
       ((:W "SDL_SCANCODE_W"))
       ((:X "SDL_SCANCODE_X"))
       ((:Y "SDL_SCANCODE_Y"))
       ((:Z "SDL_SCANCODE_Z"))

       ((:1 "SDL_SCANCODE_1"))
       ((:2 "SDL_SCANCODE_2"))
       ((:3 "SDL_SCANCODE_3"))
       ((:4 "SDL_SCANCODE_4"))
       ((:5 "SDL_SCANCODE_5"))
       ((:6 "SDL_SCANCODE_6"))
       ((:7 "SDL_SCANCODE_7"))
       ((:8 "SDL_SCANCODE_8"))
       ((:9 "SDL_SCANCODE_9"))
       ((:0 "SDL_SCANCODE_0"))

       ((:RETURN "SDL_SCANCODE_RETURN"))
       ((:ESCAPE "SDL_SCANCODE_ESCAPE"))
       ((:BACKSPACE "SDL_SCANCODE_BACKSPACE"))
       ((:TAB "SDL_SCANCODE_TAB"))
       ((:SPACE "SDL_SCANCODE_SPACE"))

       ((:MINUS "SDL_SCANCODE_MINUS"))
       ((:EQUALS "SDL_SCANCODE_EQUALS"))
       ((:LEFTBRACKET "SDL_SCANCODE_LEFTBRACKET"))
       ((:RIGHTBRACKET "SDL_SCANCODE_RIGHTBRACKET"))
       ((:BACKSLASH "SDL_SCANCODE_BACKSLASH"))
       ((:NONUSHASH "SDL_SCANCODE_NONUSHASH"))
       ((:SEMICOLON "SDL_SCANCODE_SEMICOLON"))
       ((:APOSTROPHE "SDL_SCANCODE_APOSTROPHE"))
       ((:GRAVE "SDL_SCANCODE_GRAVE"))
       ((:COMMA "SDL_SCANCODE_COMMA"))
       ((:PERIOD "SDL_SCANCODE_PERIOD"))
       ((:SLASH "SDL_SCANCODE_SLASH"))

       ((:CAPSLOCK "SDL_SCANCODE_CAPSLOCK"))

       ((:F1 "SDL_SCANCODE_F1"))
       ((:F2 "SDL_SCANCODE_F2"))
       ((:F3 "SDL_SCANCODE_F3"))
       ((:F4 "SDL_SCANCODE_F4"))
       ((:F5 "SDL_SCANCODE_F5"))
       ((:F6 "SDL_SCANCODE_F6"))
       ((:F7 "SDL_SCANCODE_F7"))
       ((:F8 "SDL_SCANCODE_F8"))
       ((:F9 "SDL_SCANCODE_F9"))
       ((:F10 "SDL_SCANCODE_F10"))
       ((:F11 "SDL_SCANCODE_F11"))
       ((:F12 "SDL_SCANCODE_F12"))

       ((:PRINTSCREEN "SDL_SCANCODE_PRINTSCREEN"))
       ((:SCROLLLOCK "SDL_SCANCODE_SCROLLLOCK"))
       ((:PAUSE "SDL_SCANCODE_PAUSE"))
       ((:INSERT "SDL_SCANCODE_INSERT"))
       ((:HOME "SDL_SCANCODE_HOME"))
       ((:PAGEUP "SDL_SCANCODE_PAGEUP"))
       ((:DELETE "SDL_SCANCODE_DELETE"))
       ((:END "SDL_SCANCODE_END"))
       ((:PAGEDOWN "SDL_SCANCODE_PAGEDOWN"))
       ((:RIGHT "SDL_SCANCODE_RIGHT"))
       ((:LEFT "SDL_SCANCODE_LEFT"))
       ((:DOWN "SDL_SCANCODE_DOWN"))
       ((:UP "SDL_SCANCODE_UP"))

       ((:NUMLOCKCLEAR "SDL_SCANCODE_NUMLOCKCLEAR"))
       ((:KP-DIVIDE "SDL_SCANCODE_KP_DIVIDE"))
       ((:KP-MULTIPLY "SDL_SCANCODE_KP_MULTIPLY"))
       ((:KP-MINUS "SDL_SCANCODE_KP_MINUS"))
       ((:KP-PLUS "SDL_SCANCODE_KP_PLUS"))
       ((:KP-ENTER "SDL_SCANCODE_KP_ENTER"))
       ((:KP-1 "SDL_SCANCODE_KP_1"))
       ((:KP-2 "SDL_SCANCODE_KP_2"))
       ((:KP-3 "SDL_SCANCODE_KP_3"))
       ((:KP-4 "SDL_SCANCODE_KP_4"))
       ((:KP-5 "SDL_SCANCODE_KP_5"))
       ((:KP-6 "SDL_SCANCODE_KP_6"))
       ((:KP-7 "SDL_SCANCODE_KP_7"))
       ((:KP-8 "SDL_SCANCODE_KP_8"))
       ((:KP-9 "SDL_SCANCODE_KP_9"))
       ((:KP-0 "SDL_SCANCODE_KP_0"))
       ((:KP-PERIOD "SDL_SCANCODE_KP_PERIOD"))

       ((:NONUSBACKSLASH "SDL_SCANCODE_NONUSBACKSLASH"))
       ((:APPLICATION "SDL_SCANCODE_APPLICATION"))
       ((:POWER "SDL_SCANCODE_POWER"))
       ((:KP-EQUALS "SDL_SCANCODE_KP_EQUALS"))
       ((:F13 "SDL_SCANCODE_F13"))
       ((:F14 "SDL_SCANCODE_F14"))
       ((:F15 "SDL_SCANCODE_F15"))
       ((:F16 "SDL_SCANCODE_F16"))
       ((:F17 "SDL_SCANCODE_F17"))
       ((:F18 "SDL_SCANCODE_F18"))
       ((:F19 "SDL_SCANCODE_F19"))
       ((:F20 "SDL_SCANCODE_F20"))
       ((:F21 "SDL_SCANCODE_F21"))
       ((:F22 "SDL_SCANCODE_F22"))
       ((:F23 "SDL_SCANCODE_F23"))
       ((:F24 "SDL_SCANCODE_F24"))
       ((:EXECUTE "SDL_SCANCODE_EXECUTE"))
       ((:HELP "SDL_SCANCODE_HELP"))
       ((:MENU "SDL_SCANCODE_MENU"))
       ((:SELECT "SDL_SCANCODE_SELECT"))
       ((:STOP "SDL_SCANCODE_STOP"))
       ((:AGAIN "SDL_SCANCODE_AGAIN"))
       ((:UNDO "SDL_SCANCODE_UNDO"))
       ((:CUT "SDL_SCANCODE_CUT"))
       ((:COPY "SDL_SCANCODE_COPY"))
       ((:PASTE "SDL_SCANCODE_PASTE"))
       ((:FIND "SDL_SCANCODE_FIND"))
       ((:MUTE "SDL_SCANCODE_MUTE"))
       ((:VOLUMEUP "SDL_SCANCODE_VOLUMEUP"))
       ((:VOLUMEDOWN "SDL_SCANCODE_VOLUMEDOWN"))

       ((:KP-COMMA "SDL_SCANCODE_KP_COMMA"))
       ((:KP-EQUALSAS400 "SDL_SCANCODE_KP_EQUALSAS400"))

       ((:INTERNATIONAL1 "SDL_SCANCODE_INTERNATIONAL1"))
       ((:INTERNATIONAL2 "SDL_SCANCODE_INTERNATIONAL2"))
       ((:INTERNATIONAL3 "SDL_SCANCODE_INTERNATIONAL3"))
       ((:INTERNATIONAL4 "SDL_SCANCODE_INTERNATIONAL4"))
       ((:INTERNATIONAL5 "SDL_SCANCODE_INTERNATIONAL5"))
       ((:INTERNATIONAL6 "SDL_SCANCODE_INTERNATIONAL6"))
       ((:INTERNATIONAL7 "SDL_SCANCODE_INTERNATIONAL7"))
       ((:INTERNATIONAL8 "SDL_SCANCODE_INTERNATIONAL8"))
       ((:INTERNATIONAL9 "SDL_SCANCODE_INTERNATIONAL9"))
       ((:LANG1 "SDL_SCANCODE_LANG1"))
       ((:LANG2 "SDL_SCANCODE_LANG2"))
       ((:LANG3 "SDL_SCANCODE_LANG3"))
       ((:LANG4 "SDL_SCANCODE_LANG4"))
       ((:LANG5 "SDL_SCANCODE_LANG5"))
       ((:LANG6 "SDL_SCANCODE_LANG6"))
       ((:LANG7 "SDL_SCANCODE_LANG7"))
       ((:LANG8 "SDL_SCANCODE_LANG8"))
       ((:LANG9 "SDL_SCANCODE_LANG9"))

       ((:ALTERASE "SDL_SCANCODE_ALTERASE"))
       ((:SYSREQ "SDL_SCANCODE_SYSREQ"))
       ((:CANCEL "SDL_SCANCODE_CANCEL"))
       ((:CLEAR "SDL_SCANCODE_CLEAR"))
       ((:PRIOR "SDL_SCANCODE_PRIOR"))
       ((:RETURN2 "SDL_SCANCODE_RETURN2"))
       ((:SEPARATOR "SDL_SCANCODE_SEPARATOR"))
       ((:OUT "SDL_SCANCODE_OUT"))
       ((:OPER "SDL_SCANCODE_OPER"))
       ((:CLEARAGAIN "SDL_SCANCODE_CLEARAGAIN"))
       ((:CRSEL "SDL_SCANCODE_CRSEL"))
       ((:EXSEL "SDL_SCANCODE_EXSEL"))

       ((:KP-00 "SDL_SCANCODE_KP_00"))
       ((:KP-000 "SDL_SCANCODE_KP_000"))
       ((:THOUSANDSSEPARATOR "SDL_SCANCODE_THOUSANDSSEPARATOR"))
       ((:DECIMALSEPARATOR "SDL_SCANCODE_DECIMALSEPARATOR"))
       ((:CURRENCYUNIT "SDL_SCANCODE_CURRENCYUNIT"))
       ((:CURRENCYSUBUNIT "SDL_SCANCODE_CURRENCYSUBUNIT"))
       ((:KP-LEFTPAREN "SDL_SCANCODE_KP_LEFTPAREN"))
       ((:KP-RIGHTPAREN "SDL_SCANCODE_KP_RIGHTPAREN"))
       ((:KP-LEFTBRACE "SDL_SCANCODE_KP_LEFTBRACE"))
       ((:KP-RIGHTBRACE "SDL_SCANCODE_KP_RIGHTBRACE"))
       ((:KP-TAB "SDL_SCANCODE_KP_TAB"))
       ((:KP-BACKSPACE "SDL_SCANCODE_KP_BACKSPACE"))
       ((:KP-A "SDL_SCANCODE_KP_A"))
       ((:KP-B "SDL_SCANCODE_KP_B"))
       ((:KP-C "SDL_SCANCODE_KP_C"))
       ((:KP-D "SDL_SCANCODE_KP_D"))
       ((:KP-E "SDL_SCANCODE_KP_E"))
       ((:KP-F "SDL_SCANCODE_KP_F"))
       ((:KP-XOR "SDL_SCANCODE_KP_XOR"))
       ((:KP-POWER "SDL_SCANCODE_KP_POWER"))
       ((:KP-PERCENT "SDL_SCANCODE_KP_PERCENT"))
       ((:KP-LESS "SDL_SCANCODE_KP_LESS"))
       ((:KP-GREATER "SDL_SCANCODE_KP_GREATER"))
       ((:KP-AMPERSAND "SDL_SCANCODE_KP_AMPERSAND"))
       ((:KP-DBLAMPERSAND "SDL_SCANCODE_KP_DBLAMPERSAND"))
       ((:KP-VERTICALBAR "SDL_SCANCODE_KP_VERTICALBAR"))
       ((:KP-DBLVERTICALBAR "SDL_SCANCODE_KP_DBLVERTICALBAR"))
       ((:KP-COLON "SDL_SCANCODE_KP_COLON"))
       ((:KP-HASH "SDL_SCANCODE_KP_HASH"))
       ((:KP-SPACE "SDL_SCANCODE_KP_SPACE"))
       ((:KP-AT "SDL_SCANCODE_KP_AT"))
       ((:KP-EXCLAM "SDL_SCANCODE_KP_EXCLAM"))
       ((:KP-MEMSTORE "SDL_SCANCODE_KP_MEMSTORE"))
       ((:KP-MEMRECALL "SDL_SCANCODE_KP_MEMRECALL"))
       ((:KP-MEMCLEAR "SDL_SCANCODE_KP_MEMCLEAR"))
       ((:KP-MEMADD "SDL_SCANCODE_KP_MEMADD"))
       ((:KP-MEMSUBTRACT "SDL_SCANCODE_KP_MEMSUBTRACT"))
       ((:KP-MEMMULTIPLY "SDL_SCANCODE_KP_MEMMULTIPLY"))
       ((:KP-MEMDIVIDE "SDL_SCANCODE_KP_MEMDIVIDE"))
       ((:KP-PLUSMINUS "SDL_SCANCODE_KP_PLUSMINUS"))
       ((:KP-CLEAR "SDL_SCANCODE_KP_CLEAR"))
       ((:KP-CLEARENTRY "SDL_SCANCODE_KP_CLEARENTRY"))
       ((:KP-BINARY "SDL_SCANCODE_KP_BINARY"))
       ((:KP-OCTAL "SDL_SCANCODE_KP_OCTAL"))
       ((:KP-DECIMAL "SDL_SCANCODE_KP_DECIMAL"))
       ((:KP-HEXADECIMAL "SDL_SCANCODE_KP_HEXADECIMAL"))

       ((:LCTRL "SDL_SCANCODE_LCTRL"))
       ((:LSHIFT "SDL_SCANCODE_LSHIFT"))
       ((:LALT "SDL_SCANCODE_LALT"))
       ((:LGUI "SDL_SCANCODE_LGUI"))
       ((:RCTRL "SDL_SCANCODE_RCTRL"))
       ((:RSHIFT "SDL_SCANCODE_RSHIFT"))
       ((:RALT "SDL_SCANCODE_RALT"))
       ((:RGUI "SDL_SCANCODE_RGUI"))

       ((:MODE "SDL_SCANCODE_MODE"))

       ((:AUDIONEXT "SDL_SCANCODE_AUDIONEXT"))
       ((:AUDIOPREV "SDL_SCANCODE_AUDIOPREV"))
       ((:AUDIOSTOP "SDL_SCANCODE_AUDIOSTOP"))
       ((:AUDIOPLAY "SDL_SCANCODE_AUDIOPLAY"))
       ((:AUDIOMUTE "SDL_SCANCODE_AUDIOMUTE"))
       ((:MEDIASELECT "SDL_SCANCODE_MEDIASELECT"))
       ((:WWW "SDL_SCANCODE_WWW"))
       ((:MAIL "SDL_SCANCODE_MAIL"))
       ((:CALCULATOR "SDL_SCANCODE_CALCULATOR"))
       ((:COMPUTER "SDL_SCANCODE_COMPUTER"))
       ((:AC-SEARCH "SDL_SCANCODE_AC_SEARCH"))
       ((:AC-HOME "SDL_SCANCODE_AC_HOME"))
       ((:AC-BACK "SDL_SCANCODE_AC_BACK"))
       ((:AC-FORWARD "SDL_SCANCODE_AC_FORWARD"))
       ((:AC-STOP "SDL_SCANCODE_AC_STOP"))
       ((:AC-REFRESH "SDL_SCANCODE_AC_REFRESH"))
       ((:AC-BOOKMARKS "SDL_SCANCODE_AC_BOOKMARKS"))

       ((:BRIGHTNESSDOWN "SDL_SCANCODE_BRIGHTNESSDOWN"))
       ((:BRIGHTNESSUP "SDL_SCANCODE_BRIGHTNESSUP"))
       ((:DISPLAYSWITCH "SDL_SCANCODE_DISPLAYSWITCH"))
       ((:KBDILLUMTOGGLE "SDL_SCANCODE_KBDILLUMTOGGLE"))
       ((:KBDILLUMDOWN "SDL_SCANCODE_KBDILLUMDOWN"))
       ((:KBDILLUMUP "SDL_SCANCODE_KBDILLUMUP"))
       ((:EJECT "SDL_SCANCODE_EJECT"))
       ((:SLEEP "SDL_SCANCODE_SLEEP"))

       ((:APP1 "SDL_SCANCODE_APP1"))
       ((:APP2 "SDL_SCANCODE_APP2"))

       ((:AUDIOREWIND "SDL_SCANCODE_AUDIOREWIND"))
       ((:AUDIOFASTFORWARD "SDL_SCANCODE_AUDIOFASTFORWARD"))

       ((:NUM-SCANCODES "SDL_NUM_SCANCODES"))
       )

;; SDL_keycode.h
(ctype sdl-key-code "SDL_Keycode")
(cenum sdl-keycode
       ((:UNKNOWN "SDLK_UNKNOWN"))

       ((:RETURN "SDLK_RETURN"))
       ((:ESCAPE "SDLK_ESCAPE"))
       ((:BACKSPACE "SDLK_BACKSPACE"))
       ((:TAB "SDLK_TAB"))
       ((:SPACE "SDLK_SPACE"))
       ((:EXCLAIM "SDLK_EXCLAIM"))
       ((:QUOTEDBL "SDLK_QUOTEDBL"))
       ((:HASH "SDLK_HASH"))
       ((:PERCENT "SDLK_PERCENT"))
       ((:DOLLAR "SDLK_DOLLAR"))
       ((:AMPERSAND "SDLK_AMPERSAND"))
       ((:QUOTE "SDLK_QUOTE"))
       ((:LEFTPAREN "SDLK_LEFTPAREN"))
       ((:RIGHTPAREN "SDLK_RIGHTPAREN"))
       ((:ASTERISK "SDLK_ASTERISK"))
       ((:PLUS "SDLK_PLUS"))
       ((:COMMA "SDLK_COMMA"))
       ((:MINUS "SDLK_MINUS"))
       ((:PERIOD "SDLK_PERIOD"))
       ((:SLASH "SDLK_SLASH"))
       ((:0 "SDLK_0"))
       ((:1 "SDLK_1"))
       ((:2 "SDLK_2"))
       ((:3 "SDLK_3"))
       ((:4 "SDLK_4"))
       ((:5 "SDLK_5"))
       ((:6 "SDLK_6"))
       ((:7 "SDLK_7"))
       ((:8 "SDLK_8"))
       ((:9 "SDLK_9"))
       ((:COLON "SDLK_COLON"))
       ((:SEMICOLON "SDLK_SEMICOLON"))
       ((:LESS "SDLK_LESS"))
       ((:EQUALS "SDLK_EQUALS"))
       ((:GREATER "SDLK_GREATER"))
       ((:QUESTION "SDLK_QUESTION"))
       ((:AT "SDLK_AT"))

       ((:LEFTBRACKET "SDLK_LEFTBRACKET"))
       ((:BACKSLASH "SDLK_BACKSLASH"))
       ((:RIGHTBRACKET "SDLK_RIGHTBRACKET"))
       ((:CARET "SDLK_CARET"))
       ((:UNDERSCORE "SDLK_UNDERSCORE"))
       ((:BACKQUOTE "SDLK_BACKQUOTE"))
       ((:a "SDLK_a"))
       ((:b "SDLK_b"))
       ((:c "SDLK_c"))
       ((:d "SDLK_d"))
       ((:e "SDLK_e"))
       ((:f "SDLK_f"))
       ((:g "SDLK_g"))
       ((:h "SDLK_h"))
       ((:i "SDLK_i"))
       ((:j "SDLK_j"))
       ((:k "SDLK_k"))
       ((:l "SDLK_l"))
       ((:m "SDLK_m"))
       ((:n "SDLK_n"))
       ((:o "SDLK_o"))
       ((:p "SDLK_p"))
       ((:q "SDLK_q"))
       ((:r "SDLK_r"))
       ((:s "SDLK_s"))
       ((:t "SDLK_t"))
       ((:u "SDLK_u"))
       ((:v "SDLK_v"))
       ((:w "SDLK_w"))
       ((:x "SDLK_x"))
       ((:y "SDLK_y"))
       ((:z "SDLK_z"))

       ((:CAPSLOCK "SDLK_CAPSLOCK"))

       ((:F1 "SDLK_F1"))
       ((:F2 "SDLK_F2"))
       ((:F3 "SDLK_F3"))
       ((:F4 "SDLK_F4"))
       ((:F5 "SDLK_F5"))
       ((:F6 "SDLK_F6"))
       ((:F7 "SDLK_F7"))
       ((:F8 "SDLK_F8"))
       ((:F9 "SDLK_F9"))
       ((:F10 "SDLK_F10"))
       ((:F11 "SDLK_F11"))
       ((:F12 "SDLK_F12"))

       ((:PRINTSCREEN "SDLK_PRINTSCREEN"))
       ((:SCROLLLOCK "SDLK_SCROLLLOCK"))
       ((:PAUSE "SDLK_PAUSE"))
       ((:INSERT "SDLK_INSERT"))
       ((:HOME "SDLK_HOME"))
       ((:PAGEUP "SDLK_PAGEUP"))
       ((:DELETE "SDLK_DELETE"))
       ((:END "SDLK_END"))
       ((:PAGEDOWN "SDLK_PAGEDOWN"))
       ((:RIGHT "SDLK_RIGHT"))
       ((:LEFT "SDLK_LEFT"))
       ((:DOWN "SDLK_DOWN"))
       ((:UP "SDLK_UP"))

       ((:NUMLOCKCLEAR "SDLK_NUMLOCKCLEAR"))
       ((:KP-DIVIDE "SDLK_KP_DIVIDE"))
       ((:KP-MULTIPLY "SDLK_KP_MULTIPLY"))
       ((:KP-MINUS "SDLK_KP_MINUS"))
       ((:KP-PLUS "SDLK_KP_PLUS"))
       ((:KP-ENTER "SDLK_KP_ENTER"))
       ((:KP-1 "SDLK_KP_1"))
       ((:KP-2 "SDLK_KP_2"))
       ((:KP-3 "SDLK_KP_3"))
       ((:KP-4 "SDLK_KP_4"))
       ((:KP-5 "SDLK_KP_5"))
       ((:KP-6 "SDLK_KP_6"))
       ((:KP-7 "SDLK_KP_7"))
       ((:KP-8 "SDLK_KP_8"))
       ((:KP-9 "SDLK_KP_9"))
       ((:KP-0 "SDLK_KP_0"))
       ((:KP-PERIOD "SDLK_KP_PERIOD"))

       ((:APPLICATION "SDLK_APPLICATION"))
       ((:POWER "SDLK_POWER"))
       ((:KP-EQUALS "SDLK_KP_EQUALS"))
       ((:F13 "SDLK_F13"))
       ((:F14 "SDLK_F14"))
       ((:F15 "SDLK_F15"))
       ((:F16 "SDLK_F16"))
       ((:F17 "SDLK_F17"))
       ((:F18 "SDLK_F18"))
       ((:F19 "SDLK_F19"))
       ((:F20 "SDLK_F20"))
       ((:F21 "SDLK_F21"))
       ((:F22 "SDLK_F22"))
       ((:F23 "SDLK_F23"))
       ((:F24 "SDLK_F24"))
       ((:EXECUTE "SDLK_EXECUTE"))
       ((:HELP "SDLK_HELP"))
       ((:MENU "SDLK_MENU"))
       ((:SELECT "SDLK_SELECT"))
       ((:STOP "SDLK_STOP"))
       ((:AGAIN "SDLK_AGAIN"))
       ((:UNDO "SDLK_UNDO"))
       ((:CUT "SDLK_CUT"))
       ((:COPY "SDLK_COPY"))
       ((:PASTE "SDLK_PASTE"))
       ((:FIND "SDLK_FIND"))
       ((:MUTE "SDLK_MUTE"))
       ((:VOLUMEUP "SDLK_VOLUMEUP"))
       ((:VOLUMEDOWN "SDLK_VOLUMEDOWN"))
       ((:KP-COMMA "SDLK_KP_COMMA"))
       ((:KP-EQUALSAS400 "SDLK_KP_EQUALSAS400"))


       ((:ALTERASE "SDLK_ALTERASE"))
       ((:SYSREQ "SDLK_SYSREQ"))
       ((:CANCEL "SDLK_CANCEL"))
       ((:CLEAR "SDLK_CLEAR"))
       ((:PRIOR "SDLK_PRIOR"))
       ((:RETURN2 "SDLK_RETURN2"))
       ((:SEPARATOR "SDLK_SEPARATOR"))
       ((:OUT "SDLK_OUT"))
       ((:OPER "SDLK_OPER"))
       ((:CLEARAGAIN "SDLK_CLEARAGAIN"))
       ((:CRSEL "SDLK_CRSEL"))
       ((:EXSEL "SDLK_EXSEL"))
       ((:KP-00 "SDLK_KP_00"))
       ((:KP-000 "SDLK_KP_000"))
       ((:THOUSANDSSEPARATOR "SDLK_THOUSANDSSEPARATOR"))
       ((:DECIMALSEPARATOR "SDLK_DECIMALSEPARATOR"))
       ((:CURRENCYUNIT "SDLK_CURRENCYUNIT"))
       ((:CURRENCYSUBUNIT "SDLK_CURRENCYSUBUNIT"))
       ((:KP-LEFTPAREN "SDLK_KP_LEFTPAREN"))
       ((:KP-RIGHTPAREN "SDLK_KP_RIGHTPAREN"))
       ((:KP-LEFTBRACE "SDLK_KP_LEFTBRACE"))
       ((:KP-RIGHTBRACE "SDLK_KP_RIGHTBRACE"))
       ((:KP-TAB "SDLK_KP_TAB"))
       ((:KP-BACKSPACE "SDLK_KP_BACKSPACE"))
       ((:KP-A "SDLK_KP_A"))
       ((:KP-B "SDLK_KP_B"))
       ((:KP-C "SDLK_KP_C"))
       ((:KP-D "SDLK_KP_D"))
       ((:KP-E "SDLK_KP_E"))
       ((:KP-F "SDLK_KP_F"))
       ((:KP-XOR "SDLK_KP_XOR"))
       ((:KP-POWER "SDLK_KP_POWER"))
       ((:KP-PERCENT "SDLK_KP_PERCENT"))
       ((:KP-LESS "SDLK_KP_LESS"))
       ((:KP-GREATER "SDLK_KP_GREATER"))
       ((:KP-AMPERSAND "SDLK_KP_AMPERSAND"))
       ((:KP-DBLAMPERSAND "SDLK_KP_DBLAMPERSAND"))
       ((:KP-VERTICALBAR "SDLK_KP_VERTICALBAR"))
       ((:KP-DBLVERTICALBAR "SDLK_KP_DBLVERTICALBAR"))
       ((:KP-COLON "SDLK_KP_COLON"))
       ((:KP-HASH "SDLK_KP_HASH"))
       ((:KP-SPACE "SDLK_KP_SPACE"))
       ((:KP-AT "SDLK_KP_AT"))
       ((:KP-EXCLAM "SDLK_KP_EXCLAM"))
       ((:KP-MEMSTORE "SDLK_KP_MEMSTORE"))
       ((:KP-MEMRECALL "SDLK_KP_MEMRECALL"))
       ((:KP-MEMCLEAR "SDLK_KP_MEMCLEAR"))
       ((:KP-MEMADD "SDLK_KP_MEMADD"))
       ((:KP-MEMSUBTRACT "SDLK_KP_MEMSUBTRACT"))
       ((:KP-MEMMULTIPLY "SDLK_KP_MEMMULTIPLY"))

       ((:KP-MEMDIVIDE "SDLK_KP_MEMDIVIDE"))
       ((:KP-PLUSMINUS "SDLK_KP_PLUSMINUS"))
       ((:KP-CLEAR "SDLK_KP_CLEAR"))
       ((:KP-CLEARENTRY "SDLK_KP_CLEARENTRY"))
       ((:KP-BINARY "SDLK_KP_BINARY"))
       ((:KP-OCTAL "SDLK_KP_OCTAL"))
       ((:KP-DECIMAL "SDLK_KP_DECIMAL"))
       ((:KP-HEXADECIMAL "SDLK_KP_HEXADECIMAL"))


       ((:LCTRL "SDLK_LCTRL"))
       ((:LSHIFT "SDLK_LSHIFT"))
       ((:LALT "SDLK_LALT"))
       ((:LGUI "SDLK_LGUI"))
       ((:RCTRL "SDLK_RCTRL"))
       ((:RSHIFT "SDLK_RSHIFT"))
       ((:RALT "SDLK_RALT"))
       ((:RGUI "SDLK_RGUI"))

       ((:MODE "SDLK_MODE"))

       ((:AUDIONEXT "SDLK_AUDIONEXT"))
       ((:AUDIOPREV "SDLK_AUDIOPREV"))
       ((:AUDIOSTOP "SDLK_AUDIOSTOP"))
       ((:AUDIOPLAY "SDLK_AUDIOPLAY"))
       ((:AUDIOMUTE "SDLK_AUDIOMUTE"))
       ((:MEDIASELECT "SDLK_MEDIASELECT"))
       ((:WWW "SDLK_WWW"))
       ((:MAIL "SDLK_MAIL"))
       ((:CALCULATOR "SDLK_CALCULATOR"))
       ((:COMPUTER "SDLK_COMPUTER"))
       ((:AC-SEARCH "SDLK_AC_SEARCH"))
       ((:AC-HOME "SDLK_AC_HOME"))
       ((:AC-BACK "SDLK_AC_BACK"))
       ((:AC-FORWARD "SDLK_AC_FORWARD"))
       ((:AC-STOP "SDLK_AC_STOP"))
       ((:AC-REFRESH "SDLK_AC_REFRESH"))
       ((:AC-BOOKMARKS "SDLK_AC_BOOKMARKS"))

       ((:BRIGHTNESSDOWN "SDLK_BRIGHTNESSDOWN"))

       ((:BRIGHTNESSUP "SDLK_BRIGHTNESSUP"))
       ((:DISPLAYSWITCH "SDLK_DISPLAYSWITCH"))
       ((:KBDILLUMTOGGLE "SDLK_KBDILLUMTOGGLE"))

       ((:KBDILLUMDOWN "SDLK_KBDILLUMDOWN"))
       ((:KBDILLUMUP "SDLK_KBDILLUMUP"))
       ((:EJECT "SDLK_EJECT"))
       ((:SLEEP "SDLK_SLEEP"))
       ((:APP1 "SDLK_APP1"))
       ((:APP2 "SDLK_APP2"))

       ((:AUDIOREWIND "SDLK_AUDIOREWIND"))
       ((:AUDIOFASTFORWARD "SDLK_AUDIOFASTFORWARD")))

(cenum sdl-keymod
       ((:NONE "KMOD_NONE"))
       ((:LSHIFT "KMOD_LSHIFT"))
       ((:RSHIFT "KMOD_RSHIFT"))
       ((:LCTRL "KMOD_LCTRL"))
       ((:RCTRL "KMOD_RCTRL"))
       ((:LALT "KMOD_LALT"))
       ((:RALT "KMOD_RALT"))
       ((:LGUI "KMOD_LGUI"))
       ((:RGUI "KMOD_RGUI"))
       ((:NUM "KMOD_NUM"))
       ((:CAPS "KMOD_CAPS"))
       ((:MODE "KMOD_MODE"))
       ((:RESERVED "KMOD_RESERVED"))
       ((:CTRL "KMOD_CTRL"))
       ((:SHIFT "KMOD_SHIFT"))
       ((:ALT "KMOD_ALT"))
       ((:GUI "KMOD_GUI")))

;; SDL_keyboard.h
(cstruct sdl-keysym "SDL_Keysym"
         (:scancode "scancode" :type sdl-scancode)
         (:sym "sym" :type sdl-key-code)
         (:mod "mod" :type Uint16)
         (:unused "unused" :type Uint32))

;; SDL_joystick.h
(cstruct sdl-joystick-guid "SDL_JoystickGUID"
         (:data "data" :type :pointer))

(ctype sdl-joystick-id "SDL_JoystickID")

(cenum sdl-joystick-type
       ((:UNKNOWN "SDL_JOYSTICK_TYPE_UNKNOWN"))
       ((:GAMECONTROLLER "SDL_JOYSTICK_TYPE_GAMECONTROLLER"))
       ((:WHEEL "SDL_JOYSTICK_TYPE_WHEEL"))
       ((:ARCADE-STICK "SDL_JOYSTICK_TYPE_ARCADE_STICK"))
       ((:FLIGHT-STICK "SDL_JOYSTICK_TYPE_FLIGHT_STICK"))
       ((:DANCE-PAD "SDL_JOYSTICK_TYPE_DANCE_PAD"))
       ((:GUITAR "SDL_JOYSTICK_TYPE_GUITAR"))
       ((:DRUM-KIT "SDL_JOYSTICK_TYPE_DRUM_KIT"))
       ((:ARCADE-PAD "SDL_JOYSTICK_TYPE_ARCADE_PAD"))
       ((:THROTTLE "SDL_JOYSTICK_TYPE_THROTTLE")))

(cenum sdl-joystick-power-level
       ((:UNKNOWN "SDL_JOYSTICK_POWER_UNKNOWN"))
       ((:EMPTY "SDL_JOYSTICK_POWER_EMPTY"))
       ((:LOW "SDL_JOYSTICK_POWER_LOW"))
       ((:MEDIUM "SDL_JOYSTICK_POWER_MEDIUM"))
       ((:FULL "SDL_JOYSTICK_POWER_FULL"))
       ((:WIRED "SDL_JOYSTICK_POWER_WIRED"))
       ((:MAX "SDL_JOYSTICK_POWER_MAX")))

(constant (+SDL-JOYSTICK-AXIS-MAX+ "SDL_JOYSTICK_AXIS_MAX"))
(constant (+SDL-JOYSTICK-AXIS-MIN+ "SDL_JOYSTICK_AXIS_MIN"))
(constant (+SDL-HAT-CENTERED+ "SDL_HAT_CENTERED"))
(constant (+SDL-HAT-UP+ "SDL_HAT_UP"))
(constant (+SDL-HAT-RIGHT+ "SDL_HAT_RIGHT"))
(constant (+SDL-HAT-DOWN+ "SDL_HAT_DOWN"))
(constant (+SDL-HAT-LEFT+ "SDL_HAT_LEFT"))
(constant (+SDL-HAT-RIGHTUP+ "SDL_HAT_RIGHTUP"))
(constant (+SDL-HAT-RIGHTDOWN+ "SDL_HAT_RIGHTDOWN"))
(constant (+SDL-HAT-LEFTUP+ "SDL_HAT_LEFTUP"))
(constant (+SDL-HAT-LEFTDOWN+ "SDL_HAT_LEFTDOWN"))

;; SDL_touch.h
(ctype sdl-touch-id "SDL_TouchID")
(ctype sdl-finger-id "SDL_FingerID")

;; SDL_gesture.h
(ctype sdl-gesture-id "SDL_GestureID")

;; SDL_events.h
(constant (+SDL-RELEASED+ "SDL_RELEASED"))
(constant (+SDL-PRESSED+ "SDL_PRESSED"))

(cenum sdl-event-type
       ((:FIRSTEVENT "SDL_FIRSTEVENT"))
       ((:QUIT "SDL_QUIT"))
       ((:APP-TERMINATING "SDL_APP_TERMINATING"))
       ((:APP-LOWMEMORY "SDL_APP_LOWMEMORY"))
       ((:APP-WILLENTERBACKGROUND "SDL_APP_WILLENTERBACKGROUND"))
       ((:APP-DIDENTERBACKGROUND "SDL_APP_DIDENTERBACKGROUND"))
       ((:APP-WILLENTERFOREGROUND "SDL_APP_WILLENTERFOREGROUND"))
       ((:APP-DIDENTERFOREGROUND "SDL_APP_DIDENTERFOREGROUND"))
       ((:LOCALECHANGED "SDL_LOCALECHANGED"))
       ((:DISPLAYEVENT "SDL_DISPLAYEVENT"))
       ((:WINDOWEVENT "SDL_WINDOWEVENT"))
       ((:SYSWMEVENT "SDL_SYSWMEVENT"))
       ((:KEYDOWN "SDL_KEYDOWN"))
       ((:KEYUP "SDL_KEYUP"))
       ((:TEXTEDITING "SDL_TEXTEDITING"))
       ((:TEXTINPUT "SDL_TEXTINPUT"))
       ((:KEYMAPCHANGED "SDL_KEYMAPCHANGED"))
       ((:MOUSEMOTION "SDL_MOUSEMOTION"))
       ((:MOUSEBUTTONDOWN "SDL_MOUSEBUTTONDOWN"))
       ((:MOUSEBUTTONUP "SDL_MOUSEBUTTONUP"))
       ((:MOUSEWHEEL "SDL_MOUSEWHEEL"))
       ((:JOYAXISMOTION "SDL_JOYAXISMOTION"))
       ((:JOYBALLMOTION "SDL_JOYBALLMOTION"))
       ((:JOYHATMOTION "SDL_JOYHATMOTION"))
       ((:JOYBUTTONDOWN "SDL_JOYBUTTONDOWN"))
       ((:JOYBUTTONUP "SDL_JOYBUTTONUP"))
       ((:JOYDEVICEADDED "SDL_JOYDEVICEADDED"))
       ((:JOYDEVICEREMOVED "SDL_JOYDEVICEREMOVED"))
       ((:CONTROLLERAXISMOTION "SDL_CONTROLLERAXISMOTION"))
       ((:CONTROLLERBUTTONDOWN "SDL_CONTROLLERBUTTONDOWN"))
       ((:CONTROLLERBUTTONUP "SDL_CONTROLLERBUTTONUP"))
       ((:CONTROLLERDEVICEADDED "SDL_CONTROLLERDEVICEADDED"))
       ((:CONTROLLERDEVICEREMOVED "SDL_CONTROLLERDEVICEREMOVED"))
       ((:CONTROLLERDEVICEREMAPPED "SDL_CONTROLLERDEVICEREMAPPED"))
       ((:CONTROLLERTOUCHPADDOWN "SDL_CONTROLLERTOUCHPADDOWN"))
       ((:CONTROLLERTOUCHPADMOTION "SDL_CONTROLLERTOUCHPADMOTION"))
       ((:CONTROLLERTOUCHPADUP "SDL_CONTROLLERTOUCHPADUP"))
       ((:CONTROLLERSENSORUPDATE "SDL_CONTROLLERSENSORUPDATE"))
       ((:FINGERDOWN "SDL_FINGERDOWN"))
       ((:FINGERUP "SDL_FINGERUP"))
       ((:FINGERMOTION "SDL_FINGERMOTION"))
       ((:DOLLARGESTURE "SDL_DOLLARGESTURE"))
       ((:DOLLARRECORD "SDL_DOLLARRECORD"))
       ((:MULTIGESTURE "SDL_MULTIGESTURE"))
       ((:CLIPBOARDUPDATE "SDL_CLIPBOARDUPDATE"))
       ((:DROPFILE "SDL_DROPFILE"))
       ((:DROPTEXT "SDL_DROPTEXT"))
       ((:DROPBEGIN "SDL_DROPBEGIN"))
       ((:DROPCOMPLETE "SDL_DROPCOMPLETE"))
       ((:AUDIODEVICEADDED "SDL_AUDIODEVICEADDED"))
       ((:AUDIODEVICEREMOVED "SDL_AUDIODEVICEREMOVED"))
       ((:SENSORUPDATE "SDL_SENSORUPDATE"))
       ((:RENDER-TARGETS-RESET "SDL_RENDER_TARGETS_RESET"))
       ((:RENDER-DEVICE-RESET "SDL_RENDER_DEVICE_RESET"))
       ((:USEREVENT "SDL_USEREVENT"))
       ((:LASTEVENT "SDL_LASTEVENT")))

(cstruct sdl-common-event "SDL_CommonEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32))

(cstruct sdl-display-event "SDL_DisplayEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:display "display" :type Uint32)
         (:event "event" :type Uint8)
         (:padding1 "padding1" :type Uint8)
         (:padding2 "padding2" :type Uint8)
         (:padding3 "padding3" :type Uint8)
         (:data1 "data1" :type Sint32))

(cstruct sdl-window-event "SDL_WindowEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:windowID "windowID" :type Uint32)
         (:event "event" :type Uint8)
         (:padding1 "padding1" :type Uint8)
         (:padding2 "padding2" :type Uint8)
         (:padding3 "padding3" :type Uint8)
         (:data1 "data1" :type Sint32)
         (:data2 "data2" :type Sint32))

(cstruct sdl-keyboard-event "SDL_KeyboardEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:windowID "windowID" :type Uint32)
         (:state "state" :type Uint8)
         (:repeat "repeat" :type Uint8)
         (:padding2 "padding2" :type Uint8)
         (:padding3 "padding3" :type Uint8)
         (:keysym "keysym" :type sdl-keysym))

(constant (+SDL-TEXTEDITINGEVENT-TEXT-SIZE+ "SDL_TEXTEDITINGEVENT_TEXT_SIZE"))
(constant (+SDL-TEXTINPUTEVENT-TEXT-SIZE+ "SDL_TEXTINPUTEVENT_TEXT_SIZE"))

(cstruct sdl-text-editing-event "SDL_TextEditingEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:windowID "windowID" :type Uint32)
         (:text "text" :type :string)
         (:start "start" :type Sint32)
         (:length "length" :type Sint32))

(cstruct sdl-text-input-event "SDL_TextInputEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:windowID "windowID" :type Uint32)
         (:text "text" :type :pointer))

(cstruct sdl-mouse-motion-event "SDL_MouseMotionEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:windowID "windowID" :type Uint32)
         (:which "which" :type Uint32)
         (:state "state" :type Uint32)
         (:x "x" :type Sint32)
         (:y "y" :type Sint32)
         (:xrel "xrel" :type Sint32)
         (:yrel "yrel" :type Sint32))

(cstruct sdl-mouse-button-event "SDL_MouseButtonEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:windowID "windowID" :type Uint32)
         (:which "which" :type Uint32)
         (:button "button" :type Uint8)
         (:state "state" :type Uint8)
         (:clicks "clicks" :type Uint8)
         (:padding1 "padding1" :type Uint8)
         (:x "x" :type Sint32)
         (:y "y" :type Sint32))

(cstruct sdl-mouse-wheel-event "SDL_MouseWheelEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:windowID "windowID" :type Uint32)
         (:which "which" :type Uint32)
         (:x "x" :type Sint32)
         (:y "y" :type Sint32)
         (:direction "direction" :type Uint32))

(cstruct sdl-joy-axis-event "SDL_JoyAxisEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type sdl-joystick-id)
         (:axis "axis" :type Uint8)
         (:padding1 "padding1" :type Uint8)
         (:padding2 "padding2" :type Uint8)
         (:padding3 "padding3" :type Uint8)
         (:value "value" :type Sint16)
         (:padding4 "padding4" :type Uint16))

(cstruct sdl-joy-ball-event "SDL_JoyBallEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type sdl-joystick-id)
         (:ball "ball" :type Uint8)
         (:padding1 "padding1" :type Uint8)
         (:padding2 "padding2" :type Uint8)
         (:padding3 "padding3" :type Uint8)
         (:xrel "xrel" :type Sint16)
         (:yrel "yrel" :type Sint16))

(cstruct sdl-joy-hat-event "SDL_JoyHatEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type sdl-joystick-id)
         (:hat "hat" :type Uint8)
         (:value "value" :type Uint8)
         (:padding1 "padding1" :type Uint8)
         (:padding2 "padding2" :type Uint8))

(cstruct sdl-joy-button-event "SDL_JoyButtonEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type sdl-joystick-id)
         (:button "button" :type Uint8)
         (:state "state" :type Uint8)
         (:padding1 "padding1" :type Uint8)
         (:padding2 "padding2" :type Uint8))

(cstruct sdl-joy-device-event "SDL_JoyDeviceEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type Sint32))

(cstruct sdl-controller-axis-event "SDL_ControllerAxisEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type sdl-joystick-id)
         (:axis "axis" :type Uint8)
         (:padding1 "padding1" :type Uint8)
         (:padding2 "padding2" :type Uint8)
         (:padding3 "padding3" :type Uint8)
         (:value "value" :type Sint16)
         (:padding4 "padding4" :type Uint16))

(cstruct sdl-controller-button-event "SDL_ControllerButtonEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type sdl-joystick-id)
         (:button "button" :type Uint8)
         (:state "state" :type Uint8)
         (:padding1 "padding1" :type Uint8)
         (:padding2 "padding2" :type Uint8))

(cstruct sdl-controller-device-event "SDL_ControllerDeviceEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type Sint32))

(cstruct sdl-controller-touchpad-event "SDL_ControllerTouchpadEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type sdl-joystick-id)
         (:touchpad "touchpad" :type Sint32)
         (:finger "finger" :type Sint32)
         (:x "x" :type :float)
         (:y "y" :type :float)
         (:pressure "pressure" :type :float))

(cstruct sdl-controller-sensor-event "SDL_ControllerSensorEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type sdl-joystick-id)
         (:sensor "sensor" :type Sint32)
         (:data "data" :type :float :count 3))

(cstruct sdl-audio-device-event "SDL_AudioDeviceEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type Uint32)
         (:iscapture "iscapture" :type Uint8)
         (:padding1 "padding1" :type Uint8)
         (:padding2 "padding2" :type Uint8)
         (:padding3 "padding3" :type Uint8))

(cstruct sdl-touch-finger-event "SDL_TouchFingerEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:touchId "touchId" :type sdl-touch-id)
         (:fingerId "fingerId" :type sdl-finger-id)
         (:x "x" :type :float)
         (:y "y" :type :float)
         (:dx "dx" :type :float)
         (:dy "dy" :type :float)
         (:pressure "pressure" :type :float)
         (:windowID "windowID" :type Uint32))

(cstruct sdl-multi-gesture-event "SDL_MultiGestureEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:touchId "touchId" :type sdl-touch-id)
         (:dTheta "dTheta" :type :float)
         (:dDist "dDist" :type :float)
         (:x "x" :type :float)
         (:y "y" :type :float)
         (:numFingers "numFingers" :type Uint16)
         (:padding "padding" :type Uint16))

(cstruct sdl-dollar-gesture-event "SDL_DollarGestureEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:touchId "touchId" :type sdl-touch-id)
         (:gestureId "gestureId" :type sdl-gesture-id)
         (:numFingers "numFingers" :type Uint32)
         (:error "error" :type :float)
         (:x "x" :type :float)
         (:y "y" :type :float))

(cstruct sdl-drop-event "SDL_DropEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:file "file" :type :string)
         (:windowID "windowID" :type Uint32))

(cstruct sdl-sensor-event "SDL_SensorEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:which "which" :type Sint32)
         (:data "data" :type :float :count 6))

(cstruct sdl-quit-event "SDL_QuitEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32))

(cstruct sdl-os-oevent "SDL_OSEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32))

(cstruct sdl-user-event "SDL_UserEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:windowID "windowID" :type Uint32)
         (:code "code" :type Sint32)
         (:data1 "data1" :type :pointer)
         (:data2 "data2" :type :pointer))

(cstruct sdl-sys-wm-event "SDL_SysWMEvent"
         (:type "type" :type Uint32)
         (:timestamp "timestamp" :type Uint32)
         (:msg "msg" :type :pointer))

;; union of all events
(cunion sdl-event "SDL_Event"
        (:type "type" :type Uint32)
        (:common "common" :type sdl-common-event)
        (:display "display" :type sdl-display-event)
        (:window "window" :type sdl-window-event)
        (:key "key" :type sdl-keyboard-event)
        (:edit "edit" :type sdl-text-editing-event)
        (:text "text" :type sdl-text-input-event)
        (:motion "motion" :type sdl-mouse-motion-event)
        (:button "button" :type sdl-mouse-button-event)
        (:wheel "wheel" :type sdl-mouse-wheel-event)
        (:jaxis "jaxis" :type sdl-joy-axis-event)
        (:jball "jball" :type sdl-joy-ball-event)
        (:jhat "jhat" :type sdl-joy-hat-event)
        (:jbutton "jbutton" :type sdl-joy-button-event)
        (:jdevice "jdevice" :type sdl-joy-device-event)
        (:caxis "caxis" :type sdl-controller-axis-event)
        (:cbutton "cbutton" :type sdl-controller-button-event)
        (:cdevice "cdevice" :type sdl-controller-device-event)
        (:ctouchpad "ctouchpad" :type sdl-controller-touchpad-event)
        (:csensor "csensor" :type sdl-controller-sensor-event)
        (:adevice "adevice" :type sdl-audio-device-event)
        (:sensor "sensor" :type sdl-sensor-event)
        (:quit "quit" :type sdl-quit-event)
        (:user "user" :type sdl-user-event)
        (:syswm "syswm" :type sdl-sys-wm-event)
        (:tfinger "tfinger" :type sdl-touch-finger-event)
        (:mgesture "mgesture" :type sdl-multi-gesture-event)
        (:dgesture "dgesture" :type sdl-dollar-gesture-event)
        (:drop "drop" :type sdl-drop-event)
        (:padding "padding" :type Uint8 :count 56))

(cenum sdl-event-action
       ((:add-event "SDL_ADDEVENT"))
       ((:peek-event"SDL_PEEKEVENT"))
       ((:get-event "SDL_GETEVENT")))

(constant (+SDL-QUERY+ "SDL_QUERY"))
(constant (+SDL-IGNORE+ "SDL_IGNORE"))
(constant (+SDL-DISABLE+ "SDL_DISABLE"))
(constant (+SDL-ENABLE+ "SDL_ENABLE"))
