(defpackage #:cl-sdl2
  (:use :cl :cffi)
  (:export
   ;; utilities
   :+NULL+
   :join-flags
   ;; constants
   :+SDL-INIT-TIMER+
   :+SDL-INIT-AUDIO+
   :+SDL-INIT-VIDEO+
   :+SDL-INIT-JOYSTICK+
   :+SDL-INIT-HAPTIC+
   :+SDL-INIT-GAMECONTROLLER+
   :+SDL-INIT-EVENTS+
   :+SDL-INIT-SENSOR+
   :+SDL-INIT-NOPARACHUTE+
   :+SDL-INIT-EVERYTHING+
   :+SDL-ALPHA-OPAQUE+
   :+SDL-ALPHA-TRANSPARENT+
   :+SDL-SWSURFACE
   :+SDL-PREALLOC+
   :+SDL-RLEACCEL+
   :+SDL-DONTFREE+
   :+SDL-SIMD-ALIGNED+
   :+SDL-JOYSTICK-AXIS-MAX+
   :+SDL-JOYSTICK-AXIS-MIN+
   :+SDL-HAT-CENTERED+
   :+SDL-HAT-UP+
   :+SDL-HAT-RIGHT+
   :+SDL-HAT-DOWN+
   :+SDL-HAT-LEFT+
   :+SDL-HAT-RIGHTUP+
   :+SDL-HAT-RIGHTDOWN+
   :+SDL-HAT-LEFTUP+
   :+SDL-HAT-LEFTDOWN+
   :+SDL-RELEASED+
   :+SDL-PRESSED+
   :+SDL-TEXTEDITINGEVENT-TEXT-SIZE+
   :+SDL-TEXTINPUTEVENT-TEXT-SIZE+
   :+SDL-QUERY+
   :+SDL-IGNORE+
   :+SDL-DISABLE+
   :+SDL-ENABLE+
   ;; basic types
   :size-t
   :sdl-timer-id
   :sdl-key-code
   :sdl-joystick-id
   :sdl-touch-id
   :sdl-finger-id
   :sdl-gesture-id
   ;; unions
   :sdl-event
   ;; structs
   :sdl-color
   :sdl-palette
   :sdl-pixelformat
   :sdl-point
   :sdl-point
   :sdl-rect
   :sdl-rect
   :sdl-surface
   :sdl-display-mode
   :sdl-keysym
   :sdl-joystick-guid
   :sdl-common-event
   :sdl-display-event
   :sdl-window-event
   :sdl-keyboard-event
   :sdl-text-editing-event
   :sdl-text-input-event
   :sdl-mouse-motion-event
   :sdl-mouse-button-event
   :sdl-mouse-wheel-event
   :sdl-joy-axis-event
   :sdl-joy-ball-event
   :sdl-joy-hat-event
   :sdl-joy-button-event
   :sdl-joy-device-event
   :sdl-controller-axis-event
   :sdl-controller-button-event
   :sdl-controller-device-event
   :sdl-controller-touchpad-event
   :sdl-controller-sensor-event
   :sdl-audio-device-event
   :sdl-touch-finger-event
   :sdl-multi-gesture-event
   :sdl-dollar-gesture-event
   :sdl-drop-event
   :sdl-sensor-event
   :sdl-quit-event
   :sdl-os-oevent
   :sdl-user-event
   :sdl-sys-wm-event
   ;; enums
   :sdl-bool
   :sdl-pixeltype
   :sdl-packedorder
   :sdl-arrayorder
   :sdl-packedlayout
   :sdl-pixelformatenum
   :sdl-blend-mode
   :sdl-blend-operation
   :sdl-blend-factor
   :sdl-yuv-conversion-mode
   :sdl-window-flags
   :sdl-window-event-id
   :sdl-display-event-id
   :sdl-display-orientation
   :sdl-gl-attr
   :sdl-gl-profile
   :sdl-gl-context-flag
   :sdl-gl-context-release-flag
   :sdl-gl-context-reset-notification
   :sdl-hit-test-result
   :sdl-scancode
   :sdl-keycode
   :sdl-keymod
   :sdl-joystick-type
   :sdl-joystick-power-level
   :sdl-event-type
   :sdl-event-action
   ;; SDL APIs
   :SDL-Init
   :SDL-InitSubSystem
   :SDL-QuitSubSystem
   :SDL-WasInit
   :SDL-Quit
   :SDL-GetMemoryFunctions
   :SDL-SetMemoryFunctions
   :SDL-GetNumAllocations
   :SDL-getenv
   :SDL-setenv
   :SDL-qsort
   :SDL-abs
   :SDL-isdigit
   :SDL-isspace
   :SDL-isupper
   :SDL-islower
   :SDL-toupper
   :SDL-tolower
   :SDL-crc32
   :SDL-memset
   :SDL-GetPixelFormatName
   :SDL-PixelFormatEnumToMasks
   :SDL-MasksToPixelFormatEnum
   :SDL-AllocFormat
   :SDL-FreeFormat
   :SDL-AllocPalette
   :SDL-SetPixelFormatPalette
   :SDL-SetPaletteColors
   :SDL-MapRGB
   :SDL-MapRGBA
   :SDL-GetRGB
   :SDL-GetRGBA
   :SDL-CalculateGammaRamp
   :SDL-GetKeyboardFocus
   :SDL-GetKeyboardState
   :SDL-GetModState
   :SDL-SetModState
   :SDL-GetKeyFromScancode
   :SDL-GetScancodeFromKey
   :SDL-GetScancodeName
   :SDL-GetScancodeFromName
   :SDL-GetKeyName
   :SDL-GetKeyFromName
   :SDL-StartTextInput
   :SDL-IsTextInputActive
   :SDL-StopTextInput
   :SDL-SetTextInputRect
   :SDL-LockJoysticks
   :SDL-UnlockJoysticks
   :SDL-NumJoysticks
   :SDL-JoystickNameForIndex
   :SDL-JoystickGetDevicePlayerIndex
   :SDL-JoystickGetDeviceGUID
   :SDL-JoystickGetDeviceVendor
   :SDL-JoystickGetDeviceProduct
   :SDL-JoystickGetDeviceProductVersion
   :SDL-JoystickGetDeviceType
   :SDL-JoystickGetDeviceInstanceID
   :SDL-JoystickOpen
   :SDL-JoystickFromInstanceID
   :SDL-JoystickFromPlayerIndex
   :SDL-JoystickAttachVirtual
   :SDL-JoystickDetachVirtual
   :SDL-JoystickIsVirtual
   :SDL-JoystickSetVirtualAxis
   :SDL-JoystickSetVirtualButton
   :SDL-JoystickSetVirtualHat
   :SDL-JoystickName
   :SDL-JoystickGetPlayerIndex
   :SDL-JoystickSetPlayerIndex
   :SDL-JoystickGetGUID
   :SDL-JoystickGetVendor
   :SDL-JoystickGetProduct
   :SDL-JoystickGetProductVersion
   :SDL-JoystickGetSerial
   :SDL-JoystickGetType
   :SDL-JoystickGetGUIDString
   :SDL-JoystickGetGUIDFromString
   :SDL-JoystickGetAttached
   :SDL-JoystickInstanceID
   :SDL-JoystickNumAxes
   :SDL-JoystickNumBalls
   :SDL-JoystickNumHats
   :SDL-JoystickNumButtons
   :SDL-JoystickUpdate
   :SDL-JoystickEventState
   :SDL-JoystickGetAxis
   :SDL-JoystickGetAxisInitialState
   :SDL-JoystickGetHat
   :SDL-JoystickGetBall
   :SDL-JoystickGetButton
   :SDL-JoystickRumble
   :SDL-JoystickRumbleTriggers
   :SDL-JoystickHasLED
   :SDL-JoystickSetLED
   :SDL-JoystickClose
   :SDL-JoystickCurrentPowerLevel
   :SDL-PumpEvents
   :SDL-PeepEvents
   :SDL-HasEvent
   :SDL-HasEvents
   :SDL-FlushEvent
   :SDL-FlushEvents
   :SDL-PollEvent
   :SDL-WaitEvent
   :SDL-WaitEventTimeout
   :SDL-PushEvent
   :SDL-SetEventFilter
   :SDL-GetEventFilter
   :SDL-AddEventWatch
   :SDL-DelEventWatch
   :SDL-FilterEvents
   :SDL-EventState
   :SDL-RegisterEvents
   :SDL-HasIntersection
   :SDL-IntersectRect
   :SDL-UnionRect
   :SDL-EnclosePoints
   :SDL-IntersectRectAndLine
   :SDL-ComposeCustomBlendMode
   :SDL-CreateRGBSurface
   :SDL-CreateRGBSurfaceWithFormat
   :SDL-CreateRGBSurfaceFrom
   :SDL-CreateRGBSurfaceWithFormatFrom
   :SDL-FreeSurface
   :SDL-SetSurfacePalette
   :SDL-LockSurface
   :SDL-UnlockSurface
   :SDL-LoadBMP-RW
   :SDL-SaveBMP-RW
   :SDL-SetSurfaceRLE
   :SDL-HasSurfaceRLE
   :SDL-SetColorKey
   :SDL-HasColorKey
   :SDL-GetColorKey
   :SDL-SetSurfaceColorMod
   :SDL-GetSurfaceColorMod
   :SDL-SetSurfaceAlphaMod
   :SDL-GetSurfaceAlphaMod
   :SDL-SetSurfaceBlendMode
   :SDL-GetSurfaceBlendMode
   :SDL-SetClipRect
   :SDL-GetClipRect
   :SDL-DuplicateSurface
   :SDL-ConvertSurface
   :SDL-ConvertSurfaceFormat
   :SDL-ConvertPixels
   :SDL-FillRect
   :SDL-FillRects
   :SDL-UpperBlit
   :SDL-LowerBlit
   :SDL-SoftStretch
   :SDL-UpperBlitScaled
   :SDL-LowerBlitScaled
   :SDL-SetYUVConversionMode
   :SDL-GetYUVConversionMode
   :SDL-GetYUVConversionModeForResolution
   :SDL-IsGameController
   :SDL-GetTicks
   :SDL-GetPerformanceCounter
   :SDL-GetPerformanceFrequency
   :SDL-Delay
   :SDL-AddTimer
   :SDL-RemoveTimer
   :SDL-GetNumVideoDrivers
   :SDL-GetVideoDriver
   :SDL-VideoInit
   :SDL-VideoQuit
   :SDL-GetCurrentVideoDriver
   :SDL-GetNumVideoDisplays
   :SDL-GetDisplayName
   :SDL-GetDisplayBounds
   :SDL-GetDisplayUsableBounds
   :SDL-GetDisplayDPI
   :SDL-GetDisplayOrientation
   :SDL-GetNumDisplayModes
   :SDL-GetDisplayMode
   :SDL-GetDesktopDisplayMOde
   :SDL-GetCurrentDisplayMode
   :SDL-GetClosestDisplayMode
   :SDL-GetWindowDisplayIndex
   :SDL-SetWindowDisplayMode
   :SDL-GetWindowDisplayMode
   :SDL-GetWindowPixelFormat
   :SDL-CreateWindow
   :SDL-CreateWindowFrom
   :SDL-GetWindowID
   :SDL-GetWindowFromID
   :SDL-GetWindowFlags
   :SDL-SetWindowTitle
   :SDL-GetWindowTitle
   :SDL-SetWindowIcon
   :SDL-SetWindowData
   :SDL-GetWindowData
   :SDL-SetWindowPosition
   :SDL-GetWindowPosition
   :SDL-SetWindowSize
   :SDL-GetWindowSize
   :SDL-GetWindowBordersSize
   :SDL-SetWindowMinimumSize
   :SDL-GetWindowMinimumSize
   :SDL-SetWindowMaximumSize
   :SDL-GetWindowMaximumSize
   :SDL-SetWindowBordered
   :SDL-SetWindowResizable
   :SDL-ShowWindow
   :SDL-HideWindow
   :SDL-RaiseWindow
   :SDL-MaximizeWindow
   :SDL-MinimizeWindow
   :SDL-RestoreWindow
   :SDL-SetWindowFullscreen
   :SDL-GetWindowSurface
   :SDL-UpdateWindowSurface
   :SDL-UpdateWindowSurfaceRects
   :SDL-SetWindowGrab
   :SDL-GetWindowGrab
   :SDL-GetGrabbedWindow
   :SDL-SetWindowBrightness
   :SDL-GetWindowBrightness
   :SDL-SetWindowOpacity
   :SDL-GetWindowOpacity
   :SDL-SetWindowModalFor
   :SDL-SetWindowInputFocus
   :SDL-SetWindowGammaRamp
   :SDL-GetWindowGammaRamp
   :SDL-SetWindowHitTest
   :SDL-DestroyWindow
   :SDL-IsScreenSaverEnabled
   :SDL-EnableScreenSaver
   :SDL-DisableScreenSaver
   :SDL-GL-LoadLibrary
   :SDL-GL-GetProcAddress
   :SDL-GL-UnloadLibrary
   :SDL-GL-ExtensionSupported
   :SDL-GL-ResetAttributes
   :SDL-GL-SetAttribute
   :SDL-GL-GetAttribute
   :SDL-GL-CreateContext
   :SDL-GL-MakeCurrent
   :SDL-GL-GetCurrentWindow
   :SDL-GL-GetCurrentContext
   :SDL-GL-GetDrawableSize
   :SDL-GL-SetSwapInterval
   :SDL-GL-GetSwapInterval
   :SDL-GL-SwapWindow
   :SDL-GL-DeleteContext
   ;; Controller system
   :sdl-controller
   :sdl-controller-names
   :sdl-controller-aspects
   :sdl-controller-inputs
   :sdl-controller-handler
   :sdl-controller-response
   :sdl-controller-poll
   :make-sdl-controller
   :joystick
   :axis
   :button
   :key
   :quit
   ))
